#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

echo "MOCK PACKER BUILD"
packer version

#./.prepare_travis
#
#pip --version
#conda --version

# Validate packer config
packer validate -var-file=builder/vars.json builder/viscrna-seq.json

# Build AMI
#PACKER_LOG=true packer -machine-readable build $BUILDER builder/viscrna-seq.json | tee packer.log

echo "DONE"
